<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>39d07664-a440-4aa4-bd5d-5f1be9d77d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.categoryItem__anchor > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[5]/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.evermos.com/public/original/q:100/evermos-production/banner/upload_f611d7458f90c8a2ebc3855f67e6b551.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appSection&quot;]/div[@class=&quot;categoryItems&quot;]/div[@class=&quot;categoryItem__wrapper&quot;]/div[@class=&quot;categoryItem&quot;]/a[@class=&quot;categoryItem__anchor&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[5]/div[2]/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets.evermos.com/public/original/q:100/evermos-production/banner/upload_f611d7458f90c8a2ebc3855f67e6b551.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
